### ISSUE TITLE
Whitelist subcommands or a wildcard to block all subcommands and still be able to whitelist specific ones

### ISSUE THREAD

**Issue by Srki20** [YouHaveTrouble/CommandWhitelist#51] opened 2022-05-24 05:19 UTC
I'm having an issue where when I type /help, it will show all subcommands and reveal all the plugins that I'm using.

I'm using essentials, and I have to give permission essentials.help to the default group in order for them to use /help, otherwise it will say they don't have permission even if 'help' is whitelisted for the default group.

Due to this, I was wondering if subcommands can be whitelisted instead (same as commands) so I can whitelist only the subcommands I want people to see.

Right now, I would have to blacklist a whole bunch of subcommands in order for people to not see them which is very tedious.

Perhaps, this could be a new feature. For example, you could add an option in the config for people to choose whether they want subcommands to be whitelisted or blacklisted. Let's say if set to true, subcommands will act as a whitelist, and if set to false, subcommands will act as a blacklist.

**Comment by YouHaveTrouble** [comment] 2022-05-24 05:46
Duplicate of #33

**Closed by YouHaveTrouble** 2022-05-24 05:46 UTC
