### ISSUE TITLE
CMI aliases error (?

### ISSUE THREAD

**Issue by CroaBeast** [YouHaveTrouble/CommandWhitelist#27] opened 2021-05-11 05:07 UTC
**Describe the bug**
CMI alias commands doesn't work with the command list.

**Expected behavior**
Well, I expect that it could work I guess

**To Reproduce**
1. Have CMI and CommandWhitelist
2. Enable some aliases in the Alias.yml file of the CMI folder.
3. Add those alias in your command list.
4. Optional: Enable `use-protocollib-to-detect-commands`, both cases doesn't work.
4. Save the changes and restart the server.
6. CMI commands doesn't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/66433837/117760946-20770000-b1ec-11eb-8df5-821b5cbb00fb.png)
![image](https://user-images.githubusercontent.com/66433837/117760984-31c00c80-b1ec-11eb-9d2b-1d34789d5c2a.png)
![image](https://user-images.githubusercontent.com/66433837/117761006-3ab0de00-b1ec-11eb-8f87-79c6a3ea0572.png)

**Additional context**
CW Version: 1.7.4
CMI Version: 8.8.4.0
Server Version: git-Purpur-1092 (MC: 1.16.5)

**Comment by YouHaveTrouble** [comment] 2021-05-11 12:04
duplicate of #12 

Use commands.yml instead of cmi aliases, because tl;dr cmi aliases are hot garbage ^^

**Closed by YouHaveTrouble** 2021-05-11 12:04 UTC
Labels: bug
