### ISSUE TITLE
Compatibility issue with BentoBox

### ISSUE THREAD

**Issue by James76931** [YouHaveTrouble/CommandWhitelist#26] opened 2021-05-06 21:59 UTC
**Describe the bug**
Base gamemode commands from the BentoBox plugin cannot be accessed, but subcommands work fine. The 'No such command' message is displayed. The issue is not fixed by enabling ProtocolLib support.

**Expected behavior**
Upon running a base gamemode command such as '/ob', the command executes normally.

**To Reproduce**
1. Download and install the latest version of [BentoBox](https://github.com/BentoBoxWorld/BentoBox/releases/), and install an addon gamemode, such as [AOneBlock](https://github.com/BentoBoxWorld/AOneBlock/releases), by dragging the gamemode's jar file into the plugins/BentoBox/addons folder.
2. Allow access to the default island command by adding it to CommandWhitelist's configuration (in AOneBlock's case, that's /ob).
3. Execute the default island command in game. Note that the 'No such command' message is displayed.
4. Execute a subcommand of the default island command, such as /ob info in this example. Note that this command executes successfully, despite the main command being inaccessible.

**Comment by YouHaveTrouble** [comment] 2021-05-06 22:20
Confirmed, but looks like the issue is specific to BentoBox. Will test further

**Comment by YouHaveTrouble** [comment] 2021-05-06 22:45
Fixed in [1.7.4](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v1.7.4)

**Closed by YouHaveTrouble** 2021-05-06 22:46 UTC
Labels: bug

**Comment by James76931** [comment] 2021-05-07 14:45
Thanks!
