### ISSUE TITLE
No tab completion 1.12.2

### ISSUE THREAD

**Issue by diszeey** [YouHaveTrouble/CommandWhitelist#5] opened 2020-10-21 15:30 UTC
Hello,
tab completion doesn't work on 1.12.2 paperspigot. I have ProtocolLib v4.5.1. In console I see "/" when somebody is trying to tab completion.
![image](https://user-images.githubusercontent.com/73243246/96742300-06e2a800-13c3-11eb-991b-af26db5a35d6.png)

**Comment by YouHaveTrouble** [comment] 2020-10-21 15:48
Seems like I forgot to remove some degug.
Tab completion will work only for commands that are set as whitelisted in plugin config, that works as intended. I'll be releasing an update removing the debug feedback in console in a few moments. Sorry for the inconvinience!

**Comment by diszeey** [comment] 2020-10-21 15:57
For me tab completion dosen't work.
![image](https://user-images.githubusercontent.com/73243246/96745499-7d34d980-13c6-11eb-9500-0bed9b3dd280.png)
![image](https://user-images.githubusercontent.com/73243246/96745620-a05f8900-13c6-11eb-92ee-ffbb44fea9d9.png)
![image](https://user-images.githubusercontent.com/73243246/96745671-ace3e180-13c6-11eb-925f-02c7a672b1a0.png)

**Comment by YouHaveTrouble** [comment] 2020-10-21 16:01
Hm, I don't think legacy mode is messing with command list at all. Will take a closer look.

**Comment by YouHaveTrouble** [comment] 2020-10-21 16:41
I indeed found an issue on my side, now making sure everything works correctly after fixing it.
Will release fixed build later tonight

**Comment by YouHaveTrouble** [comment] 2020-10-21 17:23
All issues mentioned here should be fixed in [1.3.2](https://github.com/YouHaveTrouble/CommandWhitelist/releases/tag/v1.3.2).
If you still experience issues feel free to open another issue! ^^

**Closed by YouHaveTrouble** 2020-10-21 17:23 UTC
